-- PLAT-0881: quiet hours were nullable and the mobile app sent "" which Oracle stores as NULL and
-- H2 stores as ''. Normalise and stop it happening again.
UPDATE ALERT_PREFERENCE SET QUIET_HOURS_START = NULL WHERE QUIET_HOURS_START = ' ';
UPDATE ALERT_PREFERENCE SET QUIET_HOURS_END = NULL WHERE QUIET_HOURS_END = ' ';
ALTER TABLE ALERT_PREFERENCE ADD CONSTRAINT CK_ALERT_PREF_QH_START CHECK (QUIET_HOURS_START IS NULL OR LENGTH(QUIET_HOURS_START) = 5);
ALTER TABLE ALERT_PREFERENCE ADD CONSTRAINT CK_ALERT_PREF_QH_END CHECK (QUIET_HOURS_END IS NULL OR LENGTH(QUIET_HOURS_END) = 5);
