# Consumed by platform-tooling/mock-scanners/bin/sonar-scanner via the Jenkins library.
sonar.projectKey=meridian:platform-services:txn-posting-service
sonar.projectName=txn-posting-service
sonar.projectVersion=4.1.7
sonar.host.url=https://sonar.meridian.internal
sonar.login=CHANGEME-sonar-token-from-vault
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=11
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.coverage.min=15
