replicaCount: 1
image:
  repository: registry.meridian.internal/cswt/statements-api
  tag: "0.9.4"
  pullPolicy: IfNotPresent
service:
  port: 4519
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi
probes:
  path: /health
  initialDelaySeconds: 10
env:
  LOG_LEVEL: info
  SPLUNK_HEC_URL: http://splunk-hec-mock:4606/services/collector
  MERIDIAN_AUTH_MODE: jwks
vault:
  role: statements-api
  secretsPath: secret/data/cswt/statements-api
