-- PLAT-1174 dual approval for entitlement changes themselves (previously only wires had it;
-- INC-2022-0871 was one admin granting himself approver and approving his own wire).

CREATE TABLE APPROVAL_REQUEST (
    REQUEST_ID       VARCHAR2(20)   NOT NULL,
    ORGANISATION_ID  VARCHAR2(20)   NOT NULL,
    ACTION           VARCHAR2(16)   NOT NULL,
    TARGET_USER      VARCHAR2(64)   NOT NULL,
    ROLE_CODE        VARCHAR2(32)   NOT NULL,
    TARGET_ENTITLEMENT_ID VARCHAR2(20),
    REQUESTED_BY     VARCHAR2(64)   NOT NULL,
    REQUESTED_AT     TIMESTAMP      NOT NULL,
    EXPIRES_AT       TIMESTAMP      NOT NULL,
    STATUS           VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    DECIDED_BY       VARCHAR2(64),
    DECIDED_AT       TIMESTAMP,
    REASON           VARCHAR2(400),
    CONSTRAINT PK_APPROVAL_REQUEST PRIMARY KEY (REQUEST_ID),
    CONSTRAINT CK_APR_ACTION CHECK (ACTION IN ('GRANT', 'REVOKE')),
    CONSTRAINT CK_APR_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED'))
);

CREATE INDEX IX_APR_ORG_STATUS ON APPROVAL_REQUEST (ORGANISATION_ID, STATUS);
